name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Fazer checkout do código
    - name: Check out code
      uses: actions/checkout@v3

    # Passo 2: Configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Passo 3: Instalar dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Passo 4: Etapa de build
    - name: Build application
      run: |
        # Aqui você pode rodar comandos específicos para o build
        # Por exemplo, empacotar sua aplicação com setuptools, poetry ou pyinstaller
        echo "Building application..."
        python setup.py sdist bdist_wheel || echo "Skip if not using setuptools"

    # Passo 5: Executar testes
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest tests/
